version: '2'

networks:
  app-tier:
    driver: bridge
    
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3306:3306'
    volumes:
      - /mdbdata:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=155

volumes:
  mariadb_data:
    driver: local
